version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/apps/api"
    target-branch: "develop"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
      directory: "/apps/website"
      target-branch: "develop"
      schedule:
        interval: "daily"

  - package-ecosystem: "docker"
    directory: "/apps/website/build"
    target-branch: "develop"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
      directory: "/apps/api/build"
      target-branch: "develop"
      schedule:
        interval: "daily"