apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - namespace.yaml
  - quota.yaml
  - limits.yaml

  - api/deployment.yaml
  - api/service.yaml

  - website/deployment.yaml
  - website/service.yaml

  - ingress.yaml