apiVersion: v1
kind: LimitRange
metadata:
  namespace: production
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: 128Mi
        cpu: "100m"
      defaultRequest:
        cpu: "50m"
        memory: 128Mi
      type: Container