apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

images:
- name: api
  newName: ghcr.io/uninow/ci-cd-argo-api
  newTag: main_ca1a5eb
- name: web
  newName: ghcr.io/uninow/ci-cd-demo
  newTag: v0.1.47
- name: website
  newName: ghcr.io/uninow/ci-cd-argo-website
  newTag: main_6de66f5

resources:
- ./../base



configMapGenerator:
- literals:
  - APP_DOMAIN=https://ci-cd-demo.uninow.io
  name: configs
