apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

images:
- name: api
  newName: ghcr.io/uninow/ci-cd-argo-api
  newTag: main_8054fb7
- name: web
  newName: ghcr.io/uninow/ci-cd-demo
  newTag: v0.1.47

resources:
- ../base



configMapGenerator:
- literals:
  - APP_DOMAIN=https://ci-cd-demo.uninow.io
  name: configs
