apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: demo-app-audit
spec:
  project: default
  source:
    repoURL: git@github.com:UniNow/ci-cd-argo.git
    targetRevision: HEAD
    path: deploy/kustomize/production

    kustomize:

  destination:
    server: https://kubernetes.default.svc
    namespace: production