name: Apps/Website CI

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/web/**'

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Run linters
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.29
          working-directory: './apps/web'


  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [lint-go]
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: All tests passed for api
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}