name: Apps/Website CI

on:
  pull_request:
    types: [opened, synchronized, closed]
    branches:
      - develop
    paths:
      - 'apps/website/**'
  workflow_dispatch:

jobs:
  create-deployment-preview:
    if: github.event.action == 'opened'


