name: Apps/Website CI

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/web/**'

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Run linters
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.29
          working-directory: './apps/web'

  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          build: npm run build
          working-directory: apps/web
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: apps/web/public

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [ 1, 2, 3, 4, 5 ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: apps/web/public

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          start: go run cmd/web/main.go
          wait-on: "http://localhost:1323"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [lint-go, ui-chrome-tests]
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: All tests passed for api
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}